language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

addons:
  postgresql: "9.6"

services:
  - postgresql
  - mysql

# faster builds on new travis setup not using sudo
sudo: false

install:
  - '[[ -z "$CI_USER_TOKEN" ]] || composer config github-oauth.github.com ${CI_USER_TOKEN};'
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction

before_script:
  - 'mysql -e "create database codeception_test;"'
  - 'psql -c "create database codeception_test;" -U postgres'

script:
  - php ./vendor/bin/codecept run
